// Categorii de servicii pentru MeseriasLocal
export const categories = [
  {
    id: 'constructii',
    name: 'Construcții',
    icon: '🏗️',
    color: '#EF4444',
    subcategories: [
      'Zidărie',
      'Tencuieli',
      'Gresie și faianță',
      'Pardoseli',
      'Acoperișuri',
      'Renovări complete',
    ],
  },
  {
    id: 'electric',
    name: 'Electricitate',
    icon: '⚡',
    color: '#F59E0B',
    subcategories: [
      'Instalații electrice',
      'Reparații electrice',
      'Tablouri electrice',
      'Iluminat',
      'Prize și întrerupătoare',
      'Sisteme de alarmă',
    ],
  },
  {
    id: 'instalatii',
    name: 'Instalații sanitare',
    icon: '🚿',
    color: '#3B82F6',
    subcategories: [
      'Instalații apă',
      'Instalații gaz',
      'Canalizare',
      'Încălzire',
      'Climatizare',
      'Reparații urgente',
    ],
  },
  {
    id: 'curatenie',
    name: 'Curățenie',
    icon: '🧹',
    color: '#10B981',
    subcategories: [
      'Curățenie generală',
      'Curățenie după renovare',
      'Spălare geamuri',
      'Curățenie birouri',
      'Dezinfecție',
      'Întreținere regulată',
    ],
  },
  {
    id: 'gradinarit',
    name: 'Grădinărit',
    icon: '🌱',
    color: '#84CC16',
    subcategories: [
      'Amenajări grădină',
      'Tuns gazon',
      'Plantare',
      'Sisteme irigații',
      'Întreținere grădină',
      'Peisagistică',
    ],
  },
  {
    id: 'reparatii',
    name: 'Reparații generale',
    icon: '🔧',
    color: '#8B5CF6',
    subcategories: [
      'Reparații mobilier',
      'Montaj rafturi',
      'Reparații uși/ferestre',
      'Vopsitorie',
      'Reparații diverse',
      'Montaj obiecte',
    ],
  },
  {
    id: 'transport',
    name: 'Transport & Mutări',
    icon: '🚚',
    color: '#F97316',
    subcategories: [
      'Mutări locuințe',
      'Transport marfă',
      'Mutări birouri',
      'Ambalare',
      'Depozitare',
      'Transport mobilier',
    ],
  },
  {
    id: 'auto',
    name: 'Service auto',
    icon: '🚗',
    color: '#6366F1',
    subcategories: [
      'Reparații auto',
      'Întreținere auto',
      'Vulcanizare',
      'Spălătorie auto',
      'Diagnosticare',
      'Piese auto',
    ],
  },
];